# Generated by Django 2.0.1 on 2018-06-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcdc_type', models.CharField(choices=[('CCM', 'Continuous Conduction Mode'), ('DCM', 'Discontinuous Conduction Mode')], help_text='Enter the type of DC-DC converter to be modeled.', max_length=200)),
                ('name', models.CharField(help_text='Enter the name of this converter in the admin page.', max_length=200)),
                ('url', models.CharField(help_text='Enter the url to be used to access this model.', max_length=200)),
                ('input_output_transfer', models.TextField(help_text='Enter the input to output transfer function of the converter.', max_length=5000)),
                ('input_impedance', models.TextField(help_text='Enter the input impedance of the converter.', max_length=5000)),
                ('output_impedance', models.TextField(help_text='Enter the output impedance of the converter.', max_length=5000)),
                ('duty_output_transfer', models.TextField(help_text='Enter the duty to output transfer function of the converter.', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='PowerElectronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SMPS', 'Switch-Mode Power Supplies')], help_text='Enter the name of the type of power electronic circuit to be analyzed.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SMPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DCDC', 'DC-DC Converters')], help_text='Enter the name of the type of SMPS circuit to be stored.', max_length=200)),
                ('pe_circuit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_center.PowerElectronics')),
            ],
        ),
        migrations.DeleteModel(
            name='ConverterEquation',
        ),
        migrations.AddField(
            model_name='dcdc',
            name='smps_circuit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_center.SMPS'),
        ),
    ]
