# Generated by Django 2.0.1 on 2018-06-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0002_auto_20180614_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdc',
            name='dcdc_type',
            field=models.CharField(choices=[('CCM', 'Continuous Conduction Mode')], help_text='Enter the type of DC-DC converter to be modeled.', max_length=200),
        ),
    ]
