# Generated by Django 2.0.1 on 2018-06-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0003_auto_20180615_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smps',
            name='pe_circuit_type',
        ),
        migrations.AddField(
            model_name='dcdc',
            name='pe_circuit_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='design_center.PowerElectronics'),
        ),
    ]
