# Generated by Django 2.0.1 on 2018-06-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0004_auto_20180615_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdc',
            name='url',
        ),
    ]
