# Generated by Django 2.0.2 on 2018-07-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0005_auto_20180709_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designparamchoices',
            options={'ordering': ['params'], 'verbose_name': 'param', 'verbose_name_plural': 'params'},
        ),
    ]
