# Generated by Django 2.0.1 on 2018-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0005_remove_dcdc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdc',
            name='url',
            field=models.CharField(default='1', help_text='Enter the url to be used to access this model.', max_length=200),
        ),
    ]
