# Generated by Django 2.0.1 on 2018-06-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0006_dcdc_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdc',
            name='description',
            field=models.TextField(default='1', help_text='Enter a description of the circuit to be modeled.'),
        ),
    ]
