# Generated by Django 2.0.1 on 2018-06-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0007_dcdc_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignParamChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
