# Generated by Django 2.0.7 on 2018-07-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0007_auto_20180709_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCDCRecommendedComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'component',
                'verbose_name_plural': 'components',
                'ordering': ['components'],
            },
        ),
        migrations.AddField(
            model_name='dcdc',
            name='recommended_components',
            field=models.ManyToManyField(to='design_center.DCDCRecommendedComponents'),
        ),
    ]
