# Generated by Django 2.0.1 on 2018-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0008_designparamchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdc',
            name='design_params',
            field=models.ManyToManyField(limit_choices_to=[('Vin', 'Input Voltage')], to='design_center.DesignParamChoices'),
        ),
    ]
