# Generated by Django 2.0.7 on 2018-07-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0008_auto_20180719_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcdcrecommendedcomponents',
            options={'ordering': ['components'], 'verbose_name': 'component', 'verbose_name_plural': 'Components'},
        ),
    ]
