# Generated by Django 2.0.1 on 2018-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0009_dcdc_design_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdc',
            name='design_params',
            field=models.ManyToManyField(to='design_center.DesignParamChoices'),
        ),
        migrations.AlterField(
            model_name='designparamchoices',
            name='description',
            field=models.CharField(choices=[('Vin', 'Input Voltage')], max_length=300),
        ),
    ]
