# Generated by Django 2.0.7 on 2018-07-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0009_auto_20180719_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcrecommendedcomponents',
            name='equation',
            field=models.TextField(default='1', help_text='Enter the equation used to generate this recommended component.', max_length=5000),
        ),
    ]
