# Generated by Django 2.0.7 on 2018-07-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0010_dcdcrecommendedcomponents_equation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcrecommendedcomponents',
            name='circuit_name',
            field=models.CharField(default='1', help_text='Enter the name of this converter in the admin page.', max_length=200),
        ),
    ]
