# Generated by Django 2.0.1 on 2018-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0011_auto_20180622_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designparamchoices',
            name='description',
            field=models.CharField(choices=[('Vin', 'Input Voltage'), ('Vout', 'Output Voltage')], default='1', max_length=300),
        ),
    ]
