# Generated by Django 2.0.7 on 2018-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0011_dcdcrecommendedcomponents_circuit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCDCSelectedComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_components_for_analysis', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Selected Component',
                'verbose_name_plural': 'Selected Components',
                'ordering': ['selected_components_for_analysis'],
            },
        ),
        migrations.AddField(
            model_name='dcdc',
            name='selected_components',
            field=models.ManyToManyField(to='design_center.DCDCSelectedComponents'),
        ),
    ]
