# Generated by Django 2.0.1 on 2018-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0012_auto_20180622_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdc',
            name='design_params',
        ),
        migrations.AddField(
            model_name='dcdc',
            name='design_params',
            field=models.CharField(choices=[('Vin', 'Input Voltage'), ('Vout', 'Output Voltage')], default='1', help_text='Enter the design parameters to be modeled.', max_length=200),
        ),
        migrations.AlterField(
            model_name='designparamchoices',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
