# Generated by Django 2.0.7 on 2018-07-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0012_auto_20180720_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdc',
            name='efficiency',
            field=models.CharField(default='1', help_text='Enter the efficiency of the converter.', max_length=200),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='ideal_duty_ratio',
            field=models.CharField(default='1', help_text='Enter the ideal duty ratio of the converter.', max_length=200),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='ideal_ripple_current',
            field=models.CharField(default='1', help_text='Enter the ideal ripple current of the converter.', max_length=200),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='ideal_ripple_voltage',
            field=models.CharField(default='1', help_text='Enter the ideal ripple voltage of the converter.', max_length=200),
        ),
    ]
