# Generated by Django 2.0.7 on 2018-07-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0013_auto_20180724_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcdc',
            name='efficiency',
            field=models.TextField(default='1', help_text='Enter the efficiency of the converter.', max_length=1000),
        ),
    ]
