# Generated by Django 2.0.1 on 2018-06-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0013_auto_20180622_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdc',
            name='design_params',
        ),
        migrations.AddField(
            model_name='dcdc',
            name='design_params',
            field=models.ManyToManyField(to='design_center.DesignParamChoices'),
        ),
        migrations.AlterField(
            model_name='designparamchoices',
            name='description',
            field=models.CharField(choices=[('Vin', 'Input Voltage'), ('Vout', 'Output Voltage')], max_length=300),
        ),
    ]
