# Generated by Django 2.0.7 on 2018-07-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0014_auto_20180725_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCDCOpenLoopAnalysisEquations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_url', models.CharField(max_length=200)),
                ('equation_name', models.CharField(max_length=200)),
                ('equation', models.TextField(default='1', help_text='Enter the equation to be used to analyze the converter.', max_length=1000)),
            ],
            options={
                'verbose_name': 'DC/DC Analysis Equation',
                'verbose_name_plural': 'DC/DC Open-Loop Analysis Equations',
                'ordering': ['circuit_url'],
            },
        ),
        migrations.AlterModelOptions(
            name='dcdc',
            options={'ordering': ['name'], 'verbose_name': 'DC/DC Model', 'verbose_name_plural': 'DC/DC Models'},
        ),
        migrations.AlterModelOptions(
            name='dcdcrecommendedcomponents',
            options={'ordering': ['components'], 'verbose_name': 'component', 'verbose_name_plural': 'DC/DC Recommended Components'},
        ),
        migrations.AlterModelOptions(
            name='dcdcselectedcomponents',
            options={'ordering': ['selected_components_for_analysis'], 'verbose_name': 'Selected Component', 'verbose_name_plural': 'DC/DC Selected Components'},
        ),
        migrations.AlterModelOptions(
            name='designparamchoices',
            options={'ordering': ['params'], 'verbose_name': 'param', 'verbose_name_plural': 'Design Parameters'},
        ),
        migrations.AddField(
            model_name='dcdc',
            name='open_loop_analysis_equations',
            field=models.ManyToManyField(to='design_center.DCDCOpenLoopAnalysisEquations'),
        ),
    ]
