# Generated by Django 2.0.7 on 2018-07-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0015_auto_20180726_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdc',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='dcdc',
            name='ideal_duty_ratio',
        ),
        migrations.RemoveField(
            model_name='dcdc',
            name='ideal_ripple_current',
        ),
        migrations.RemoveField(
            model_name='dcdc',
            name='ideal_ripple_voltage',
        ),
    ]
