# Generated by Django 2.0.7 on 2018-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_center', '0016_auto_20180726_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcdcopenloopanalysisequations',
            name='units',
            field=models.CharField(default='1', help_text='Enter the units of the resulting equation.', max_length=200),
        ),
    ]
