# Generated by Django 2.0.5 on 2018-09-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_name', models.CharField(default='Test', help_text='Enter a circuit name for information only at the top level. Circuit names will be contained in individual model fields.', max_length=1000)),
                ('circuit_design_type', models.CharField(choices=[('FPGA', 'FPGA Design'), ('Analog', 'Analog Circuit Design'), ('Power', 'Power Electronics Circuit Design')], default=('FPGA', 'FPGA Design'), help_text='Enter the type of circuit of this circuit to be analyzed.', max_length=1000)),
                ('dc_dc_circuit_analysis', models.BooleanField(default=0, help_text='Check if this is DC/DC Circuit Analysis')),
                ('fpga_analysis', models.BooleanField(default=0, help_text='Check if this is FPGA Circuit Analysis')),
                ('analog_analysis', models.BooleanField(default=0, help_text='Check if this is Analog Circuit Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='DCDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_circuit_type', models.CharField(choices=[('SMPS', 'Switch-Mode Power Supplies')], help_text='Enter the type of power electronic circuit to be modeled.', max_length=1000)),
                ('smps_circuit_type', models.CharField(choices=[('DCDC', 'DC-DC Converters')], help_text='Enter the type of switch mode power supply to be modeled.', max_length=1000)),
                ('dcdc_type', models.CharField(choices=[('CCM', 'Continuous Conduction Mode')], help_text='Enter the type of DC-DC converter to be modeled.', max_length=1000)),
                ('name', models.CharField(help_text='Enter the name of this converter in the admin page. REQUIRED.', max_length=1000)),
                ('url', models.CharField(default='1', help_text='Enter the url to be used to access this model. REQUIRED.', max_length=1000)),
                ('description', models.TextField(default='1', help_text='Enter a description of the circuit to be modeled.')),
                ('input_output_transfer', models.TextField(help_text='Enter the input to output transfer function of the converter.', max_length=5000)),
                ('input_impedance', models.TextField(help_text='Enter the input impedance of the converter.', max_length=5000)),
                ('output_impedance', models.TextField(help_text='Enter the output impedance of the converter.', max_length=5000)),
                ('duty_output_transfer', models.TextField(help_text='Enter the duty to output transfer function of the converter.', max_length=5000)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'DC/DC Models',
                'verbose_name': 'DC/DC Model',
            },
        ),
        migrations.CreateModel(
            name='DesignParamChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['params'],
                'verbose_name_plural': 'Design Parameters',
                'verbose_name': 'param',
            },
        ),
        migrations.CreateModel(
            name='OpenLoopAnalysisEquations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_url', models.CharField(max_length=200)),
                ('equation_name', models.CharField(max_length=200)),
                ('equation', models.TextField(default='1', help_text='Enter the equation to be used to analyze the converter.', max_length=1000)),
                ('units', models.CharField(default='1', help_text='Enter the units of the resulting equation.', max_length=200)),
            ],
            options={
                'ordering': ['circuit_url'],
                'verbose_name_plural': 'DC/DC Open-Loop Analysis Equations',
                'verbose_name': 'DC/DC Analysis Equation',
            },
        ),
        migrations.CreateModel(
            name='PowerElectronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.CharField(max_length=100)),
                ('circuit_name', models.CharField(default='1', help_text='Enter the name of this converter in the admin page.', max_length=200)),
                ('equation', models.TextField(default='1', help_text='Enter the equation used to generate this recommended component.', max_length=5000)),
            ],
            options={
                'ordering': ['components'],
                'verbose_name_plural': 'DC/DC Recommended Components',
                'verbose_name': 'component',
            },
        ),
        migrations.CreateModel(
            name='SelectedComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_components_for_analysis', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['selected_components_for_analysis'],
                'verbose_name_plural': 'Selected Components',
                'verbose_name': 'Selected Component',
            },
        ),
        migrations.CreateModel(
            name='SMPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='dcdc',
            name='design_params',
            field=models.ManyToManyField(to='dynamic_models.DesignParamChoices'),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='open_loop_analysis_equations',
            field=models.ManyToManyField(to='dynamic_models.OpenLoopAnalysisEquations'),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='recommended_components',
            field=models.ManyToManyField(to='dynamic_models.RecommendedComponents'),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='selected_components',
            field=models.ManyToManyField(to='dynamic_models.SelectedComponents'),
        ),
        migrations.AddField(
            model_name='circuitdesign',
            name='dc_dc_analysis',
            field=models.ManyToManyField(to='dynamic_models.DCDC'),
        ),
    ]
