# Generated by Django 2.0.5 on 2018-09-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_auto_20180921_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcdc',
            name='duty_output_transfer',
        ),
        migrations.RemoveField(
            model_name='dcdc',
            name='input_impedance',
        ),
        migrations.RemoveField(
            model_name='dcdc',
            name='input_output_transfer',
        ),
        migrations.RemoveField(
            model_name='dcdc',
            name='output_impedance',
        ),
        migrations.AddField(
            model_name='dcdc',
            name='closed_duty_output_transfer',
            field=models.TextField(default='Default.', help_text='Enter the duty to output transfer function of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='closed_input_impedance',
            field=models.TextField(default='Default.', help_text='Enter the input impedance of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='closed_input_output_transfer',
            field=models.TextField(default='Default.', help_text='Enter the input to output transfer function of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='closed_loop_analysis',
            field=models.BooleanField(default=False, help_text='Check if this DC/DC converter will be analyzed in a closed-loop fashion.'),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='closed_output_impedance',
            field=models.TextField(default='Default.', help_text='Enter the output impedance of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='open_duty_output_transfer',
            field=models.TextField(default='Default.', help_text='Enter the duty to output transfer function of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='open_input_impedance',
            field=models.TextField(default='Default.', help_text='Enter the input impedance of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='open_input_output_transfer',
            field=models.TextField(default='Default.', help_text='Enter the input to output transfer function of the converter.', max_length=5000),
        ),
        migrations.AddField(
            model_name='dcdc',
            name='open_output_impedance',
            field=models.TextField(default='Default.', help_text='Enter the output impedance of the converter.', max_length=5000),
        ),
    ]
