# Generated by Django 2.0.5 on 2018-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_auto_20180921_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpga_circuit_type', models.CharField(choices=[('Controller', 'Controllers')], help_text='Enter the type of power electronic circuit to be modeled.', max_length=1000)),
                ('name', models.CharField(help_text='Enter the name of this converter in the admin page. REQUIRED.', max_length=1000)),
                ('url', models.CharField(default='1', help_text='Enter the url to be used to access this model. REQUIRED.', max_length=1000)),
                ('description', models.TextField(default='1', help_text='Enter a description of the circuit to be modeled.')),
                ('fpga_code', models.TextField(default='Default.', help_text='Please enter the VHDL code for the FPGA design.')),
            ],
            options={
                'verbose_name': 'FPGA Model',
                'verbose_name_plural': 'FPGA Models',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='circuitdesign',
            name='fpga_design',
            field=models.ManyToManyField(to='dynamic_models.FPGA'),
        ),
    ]
