# Generated by Django 2.0.5 on 2018-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_auto_20181114_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_type', models.CharField(choices=[('Active Filters', 'Active Filter'), ('Passive Filters', 'Passive Filter')], help_text='Enter the type of analog circuit to be modeled.', max_length=1000)),
                ('name', models.CharField(help_text='Enter the name of this design in the admin page. REQUIRED.', max_length=1000)),
                ('url', models.CharField(default='1', help_text='Enter the url to be used to access this model. REQUIRED.', max_length=1000)),
                ('description', models.TextField(default='1', help_text='Enter a description of the circuit to be modeled.')),
                ('open_input_output_transfer', models.TextField(default='Default.', help_text='Enter the input to output transfer function of the design.', max_length=5000)),
                ('open_input_impedance', models.TextField(default='Default.', help_text='Enter the input impedance of the design.', max_length=5000)),
                ('open_output_impedance', models.TextField(default='Default.', help_text='Enter the output impedance of the design.', max_length=5000)),
                ('design_params', models.ManyToManyField(to='dynamic_models.DesignParamChoices')),
                ('open_loop_analysis_equations', models.ManyToManyField(help_text='For example, efficient, output current, etc.', to='dynamic_models.OpenLoopAnalysisEquations')),
                ('recommended_components', models.ManyToManyField(to='dynamic_models.RecommendedComponents')),
                ('selected_components', models.ManyToManyField(to='dynamic_models.SelectedComponents')),
            ],
            options={
                'verbose_name_plural': 'DC/DC Models',
                'ordering': ['name'],
                'verbose_name': 'DC/DC Model',
            },
        ),
        migrations.CreateModel(
            name='AnalogElectronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dcdc',
            name='open_loop_analysis_equations',
            field=models.ManyToManyField(help_text='For example, efficient, output current, etc.', to='dynamic_models.OpenLoopAnalysisEquations'),
        ),
        migrations.AlterField(
            model_name='fpga',
            name='fpga_circuit_type',
            field=models.CharField(choices=[('Controllers', 'Controller')], help_text='Enter the type of power electronic circuit to be modeled.', max_length=1000),
        ),
        migrations.AddField(
            model_name='circuitdesign',
            name='analog_design',
            field=models.ManyToManyField(to='dynamic_models.Analog'),
        ),
    ]
